language: node_js

node_js:
  - 'lts/*'

cache: yarn

branches:
  only:
    - master

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      # Having trouble with regressions
      # just gonna ignore them with -u
      script: yarn test -u
